dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    // Monitoring
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
}

bootRun {
    jvmArgs = [
        '-Xms2g', '-Xmx4g',
        '-XX:+UseG1GC',
        '-XX:MaxGCPauseMillis=200',
        '-XX:+HeapDumpOnOutOfMemoryError',
        '-XX:HeapDumpPath=./heap-dump.hprof',
        '-Xlog:gc*:file=./gc.log:time,uptime,level,tags:filecount=5,filesize=10m'
    ]
}
